config/routes.rb
Rails.application.routes.draw do

  get 'reports/index'

  resources :keywords
  devise_for :users
  root 'welcome#index'
  get '/search' => "keywords#search", as: :search
  get '/reports' => "reports#index", as: :reports
  post '/upload-Keywords' => "keywords#import", as: :import
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :api do
    namespace :v1 do
      post 'sign_in' => "tokens#sign_in", as: :sign_in
      post 'sign_up' => "tokens#sign_up", as: :sign_up
      post 'forgot_password' => "tokens#forgot_password", as: :forgot_password
      get 'search' => "search_results#search", as: :search_api
      get 'upload_csv' => "search_results#search", as: :upload_csv
      get 'keywords' => "keywords#index", as: :keywords
      get 'keyword_details' => "keywords#show", as: :keyword_detail
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  belongs_to :user
  has_many :search_results


  def number_ads
    search_results.where(is_bottom_add: true).or(search_results.where(is_top_add: true)).size
  end




  def self.import(file, user)
    if File.extname(file.original_filename)
      CSV.foreach(file.path, headers: true) do |row|
        puts row
        GoogleScreenScrape.search(row["keyword"], user: user)
      end
    else
       raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/models/search_result.rb
class SearchResult < ApplicationRecord
  belongs_to :keyword
  scope :top_ads, -> {where(is_top_add: true)}
  scope :bottom_ads, -> {where(is_bottom_add: true)}
  scope :search_query, -> {where.not(is_top_add: true).or(where.not(is_bottom_add: true))}

  def clean_link
    if url
      url.split('&').first
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :keywords
  has_many :search_results, through: :keywords
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  before_action :get_user


  private

  def get_user
    auth_token = params[:auth_token]
    if auth_token.nil?
      render status: 404, json: {:status=>"failed", message: "Cannot find your account."}
      return
    end

    @user = User.find_by(authentication_token: auth_token)
    if @user.nil?
      render status: 404, json: {status: "failed", message: "Cannot find your account. You must be a hacker"}
      return
    end
  end

end

app/controllers/api/v1/keywords_controller.rb
class Api::V1::KeywordsController < Api::V1::BaseController

  def index
    @keywords = @user.keywords
  end

  def show
    @keywords = Keyword.find(params[:id])
  end


  def upload_keywords
    @keyword = Keyword.import(params[:file], @user)
    if @keyword
      render status: 200, json: {:status=>"success"}
    else
      respond_to do |format|
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/api/v1/search_results_controller.rb
class Api::V1::SearchResultsController < Api::V1::BaseController
  def search_keywords
    @query = params[:keyword]
    @keywords = @user.search_results.where("url like :search or content like :search or keywords.name like :search", search: "%#{params[:@query]}%")
  end
end

app/controllers/api/v1/tokens_controller.rb
class Api::V1::TokensController < ApplicationController
    def sign_in
      email = params[:email]
      password = params[:password]

      if email.nil? or password.nil?
        render status: 400,
               json: {status: "failed", message: "The request must contain the user phone number and password."}
        return
      end

      @user = User.find_by(email: email)

      if @user.nil?
        render status: 404, json: {status: "failed", message: "Invalid email or password."}
        return
      end


      if  !@user.valid_password?(password)
        render status: 400, json: {status: "failed", message: "Invalid email or password."}
      else
        respond_to do |format|
          format.json
        end
      end
    end

    def sign_up
      email = params[:email]
      password = params[:password]
      @user = User.new
      @user.email = email
      @user.password = password
      if @user.save
        render status: 200, json: {status: "success",
                                     token: @user.authentication_token, email: @user.email
                           }
      else
        respond_to do |format|
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def forgot_password
      email = params[:email]

      if email.nil?
        render status: 400,
               json: {status: "failed", message: "Please enter a valid email address."}
        return
      end

      @user = User.find_by(email: email)

      if @user.nil?
        render status: 404, json: {status: "failed", message: "Invalid email."}
        return
      else
        @user.send_reset_password_instructions
        respond_to do |format|
          format.json
        end
      end


    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :authenticate_user!
  def index
    @keywords = current_user.keywords.order("#{sort_column} #{sort_direction}").paginate(:page => params[:page], :per_page => 200)
  end

  def create
  end

  def show
    @keyword = Keyword.find(params[:id])
    @search_results = @keyword.search_results.order('id DESC')
    @top_ads = @search_results.top_ads
    @bottom_ads = @search_results.bottom_ads
    @search_query = @search_results.search_query
  end

  def search
    @q = params[:q]
    @search_results = current_user.search_results.where("url like :search or content like :search or keywords.name like :search", search: "%#{@q}%")
  end

  def search_keywords
    @query = params[:keyword]
    @keywords = @user.search_results.join(:keyword)
                    .where("url like :search or content like :search or keywords.name like :search", search: "%#{params[:@query]}%")
  end


  def import
    Keyword.import(params[:file], current_user)
    redirect_to keywords_url, notice: "keywords imported"
  end

  private
  def sortable_columns
    ["name", "price"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction
  def index
    @search_results = SearchResult.joins(:keyword).order("#{sort_column} #{sort_direction}").paginate(:page => params[:page], :per_page => 200)
  end

  private
  def sortable_columns
    ["name", "price"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "keywords.name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/api/v1/keywords_helper.rb
module Api::V1::KeywordsHelper
end

app/helpers/api/v1/search_results_helper.rb
module Api::V1::SearchResultsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "fa fa-arrow-up" : "fa fa-arrow-down"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_login_flash_messages.html.erb
<% if flash.any? %>
          <% flash.each do |name, msg| %>
              <div class="kode-alert alert<%= name == "notice" ? "4" : "9" %>">
                <a class="closed" data-dismiss="alert">×</a>
                <%= msg %>
              </div>
          <% end %>
<% end %>

app/views/application/_nav.html.erb
<header class="navbar navbar-light navbar-toggleable-md bd-navbar">
  <nav class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#"><i class="fa fa-google"></i></a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= url_for root_url %>">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <%=  link_to "My Keywords", keywords_url, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Search Results", reports_url, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
      <%= form_tag(search_url, method: "get", class: "form-inline my-2 my-lg-0") do %>
          <%= text_field_tag(:q, @q, class: "form-control mr-sm-2", placeholder: "Keyword") %>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-google"></i> &nbsp; Search</button>
      <% end %>
    </div>
  </nav>
</header>

app/views/keywords/create.html.erb
<h1>Keywords#create</h1>
<p>Find me in app/views/keywords/create.html.erb</p>

app/views/keywords/index.html.erb
<div class="row">
  <div class="col-12">
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th><%= raw sort_link "name", "Keyword" %></th>
        <th class="text-right"><%= sort_link "created_at", "Date" %></th>
      </tr>
      </thead>
      <tbody>
      <% @keywords.each do |keyword| %>
          <tr>
            <td><%= link_to keyword.name, keyword_path(keyword) %></td>
            <td class="text-right text-muted"><%= keyword.created_at.strftime("%m/%d/%Y") %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <% unless @keywords %>
        <p class="alert alert-warning">
          You have not uploaded any keyword at the moment feel free to search for keywords or upload via the url.
        </p>
    <% end %>
  </div>
</div>

app/views/keywords/search.html.erb
<div class="row">
  <div class="col-12">
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th><%= raw sort_link "keywords.name", "Keyword" %></th>
        <th><%= sort_link "price" %></th>
      </tr>
      </thead>
      <tbody>
      <% @search_results.each do |search_result| %>
          <tr>
            <td><%= search_result.keyword.name %></td>
            <td><%= search_result.clean_link %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/keywords/show.html.erb
<div class="row">
  <div class="col-12" style="margin-top: 60px;">
    <h1 class=""><%= @keyword.name %></h1>
    <div class="info-block" >
      <span>Top Ads <b class="badge badge-info"><%= @top_ads.size %></b></span> &bull; Bottom Ads <b class="badge badge-info"><%= @bottom_ads.size %></b> &bull;
      None Ads <b class="badge badge-info"><%= @search_query.size %></b> &bull;
      Total Ads <b class="badge badge-info"><%= @keyword.number_ads %></b></span>
    </div>
  </div>
</div>
<hr/>


<div class="row">
  <% @search_results.each do |search| %>
  <div class="col-12">
    <div class="card">
      <div class="card-block">
        <h4 class="card-title"><%= raw search.title %></h4>
        <h6 class="card-subtitle mb-2 text-muted">
          <%= raw search.is_top_add? || search.is_bottom_add? ? "Ads &nbsp" : ""%>
          <%= link_to search.clean_link, url_for(search.url), class: search.is_top_add? || search.is_bottom_add? ? "is-ad" : ""%>
        </h6>
        <p class="card-text"><%= search.content %></p>
      </div>
    </div>
    <br/>
  </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>Google search microservice</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render "nav" %>

<div class="container">

  <%= yield %>

</div><!-- /.container -->
</body></html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challenge</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <style type="text/css">
      body{background: #F5F5F5;}
  </style>

  <%= csrf_meta_tags %>
</head>
<body>
    <div class="login-form">
      <%= render "login_flash_messages" %>
        <%= yield %>
    </div>

</body>
</html>

app/views/reports/index.html.erb
<div class="row">
  <div class="col-12">
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th><%= raw sort_link "keywords.name", "Keyword" %></th>
        <th><%= sort_link "price" %></th>
      </tr>
      </thead>
      <tbody>
      <% @search_results.each do |search_result| %>
          <tr>
            <td><%= search_result.keyword.name %></td>
            <td><%= search_result.clean_link %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="upload-block">
  <div class="info_block">
    Drop files here  <br/>
    or
    <div class="photo-upload">
      <%= form_tag import_url, class: "form-inline fileupload",
                   multipart: true, remote: true, id: "new_keywords" do  %>
          <div>
            <span class="btn btn-success fileinput-button">
                               <i class="glyphicon glyphicon-plus"></i>
                                  <span>Add files...</span>
              <%= file_field_tag(:file, multiple: true) %>
                            </span>
          </div>
      <% end %>
    </div>
  </div>
</div>
<div class="clearfix"></div>


<div id="progress-upload">
  <script id="template-upload" type="text/x-tmpl">
                  <div class="upload">
                     {%=o.name%}   <span class="status pull-right label label-success"></span>
                     <br/>
                    <div class="progress">
                       <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                       </div>
                    </div>
                  </div>
                </script>
</div>